name: Daily

on:
  push:
  schedule:
    - cron: '02 14 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "YEAR=`date "+%Y"`" >> $GITHUB_ENV
          echo "MONTH=`date "+%m"`" >> $GITHUB_ENV
          echo "DAY=`date "+%d"`" >> $GITHUB_ENV
      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }} || true
          git switch daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }} || git switch -c daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
          git push -u origin daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker-compose exec -T blog.momee.mt bash -c "cd uni && nimble build && cd ../ && ./uni/bin/uni new:daily"
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "✏️ Add: ${{ env.YEAR }}.${{ env.MONTH }}.${{ env.DAY }}"
