name: Daily

on:
  push:
  schedule:
    - cron: '00 15 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set yesterday date as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "YEAR=`date "+%Y"`" >> $GITHUB_ENV
          echo "MONTH=`date "+%m"`" >> $GITHUB_ENV
          echo "DAY=`date -v-1d "+%d"`" >> $GITHUB_ENV
          echo "PR_TITLE=\"Add: Daily of $YEAR-$MONTH-$DAY\""
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
        run: docker-compose build
        run: docker-compose up -d
        run: docker-compose exec -T blog.momee.mt bash -c "cd uni && nimble build && cd ../ && ./uni/bin/uni check:daily"
        run: gh pr create -B main -t ${{ env.PR_TITLE }} -b ""
